
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use specific node version
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Build
      run: |
        npm install
        npm run build
        cd dist && cp index.html 404.html
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BRANCH: gh-pages
        FOLDER: dist
